### ISSUE TITLE
 rendering failed after running for a while Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by hamelg** [bitnami/bitnami-docker-grafana-image-renderer#3]
We are using the latest image bitnami/grafana-image-renderer. After few days, hundreds zombie processes are stuck and nodejs can't fork no more process.

This issue is related to https://github.com/puppeteer/puppeteer/issues/6757

Logs

```
Error: Failed to launch the browser process!
[1102/000132.270683:FATAL:zygote_host_impl_linux.cc(174)] Check failed: process.IsValid(). Failed to launch zygote process
#0 0x55d4ebb51f49 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x6aa0f48)
#1 0x55d4ebabb933 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x6a0a932)
#2 0x55d4ebacf500 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x6a1e4ff)
#3 0x55d4ebad004e (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x6a1f04d)
#4 0x55d4e9cd1752 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x4c20751)
#5 0x55d4eb66c6eb (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x65bb6ea)
#6 0x55d4e9397d7b (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x42e6d7a)
#7 0x55d4e93983c4 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x42e73c3)
#8 0x55d4eb66bc42 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x65bac41)
#9 0x55d4eb669fa5 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x65b8fa4)
#10 0x55d4eb66a0cd (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x65b90cc)
#11 0x55d4eb6c8fd9 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x6617fd8)
#12 0x55d4eb6c8cf8 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x6617cf7)
#13 0x55d4e84dcae1 ChromeMain
#14 0x7fbe34f6209b __libc_start_main
#15 0x55d4e84dc92a _start

Received signal 6
#0 0x55d4ebb51f49 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x6aa0f48)
#1 0x55d4ebabb933 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x6a0a932)
#2 0x55d4ebb51a21 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x6aa0a20)
#3 0x7fbe367f9730 (/lib/x86_64-linux-gnu/libpthread-2.28.so+0x1272f)
#4 0x7fbe34f757bb gsignal
#5 0x7fbe34f60535 abort
#6 0x55d4ebb50cb5 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x6a9fcb4)
#7 0x55d4ebacf927 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x6a1e926)
#8 0x55d4ebad004e (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x6a1f04d)
#9 0x55d4e9cd1752 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x4c20751)
#10 0x55d4eb66c6eb (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x65bb6ea)
#11 0x55d4e9397d7b (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x42e6d7a)
#12 0x55d4e93983c4 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x42e73c3)
#13 0x55d4eb66bc42 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x65bac41)
#14 0x55d4eb669fa5 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x65b8fa4)
#15 0x55d4eb66a0cd (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x65b90cc)
#16 0x55d4eb6c8fd9 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x6617fd8)
#17 0x55d4eb6c8cf8 (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome+0x6617cf7)
#18 0x55d4e84dcae1 ChromeMain
#19 0x7fbe34f6209b __libc_start_main
#20 0x55d4e84dc92a _start
  r8: 0000000000000000  r9: 00007fffcf22c150 r10: 0000000000000008 r11: 0000000000000246
 r12: 00003eba002d0000 r13: 00007fffcf22c3b0 r14: 00003eba002d0010 r15: aaaaaaaaaaaaaaaa
  di: 0000000000000002  si: 00007fffcf22c150  bp: 00007fffcf22c3a0  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fbe34f757bb  sp: 00007fffcf22c150
  ip: 00007fbe34f757bb efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
    at ChildProcess.<anonymous> (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:188:79)
    at ChildProcess.emit (events.js:412:35)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
```

Processes in the container :
```

$ ps -ea | grep -c chrome
984

$ ps -ea | grep chrome|head
 195379 ?        00:00:00 chrome <defunct>
 195380 ?        00:00:00 chrome <defunct>
 195398 ?        00:00:00 chrome <defunct>
...
```

**Environment**:
- Grafana Image Renderer version: 3.2.1
- Grafana version: 8.1.7
- OS Grafana Image Renderer is installed on: crio container on openshift 4.6
- grafana chart version : 6.1.9

**Comment by alemorcuq** [comment]
Have you tried running the container with the `init` feature as suggested in that issue?

**Comment by hamelg** [comment]
My container engine is cri-o and there is no equivalent option like docker --init.

**Comment by hamelg** [comment]
I solved the issue with this workaround by starting the node process with bash.
`/bin/bash -c "node build/app.js server --config=conf/config.json && :"`

Here, bash is used as a simple init system and reap zombie processes.
https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by javsalgar** [comment]
Thank you so much for the information! It will be useful for the community :D
